ALTER TABLE NPHIES_CLAIMINFO ADD (
PRESCRIPTION VARCHAR(255)
);
ALTER TABLE NPHIES_CLAIMITEM ADD (
PHARMACISTSELECTIONREASON  VARCHAR(255) ,
PHARMACISTSUBSTITUTE VARCHAR(255),
REASONPHARMACISTSUBSTITUTE VARCHAR(255)

);
ALTER TABLE NPHIES_CLAIMITEMDETAILS ADD (
PRESCRIBEDDRUGCODE VARCHAR2(50),
PHARMACISTSELECTIONREASON  VARCHAR(255) ,
PHARMACISTSUBSTITUTE VARCHAR(255),
REASONPHARMACISTSUBSTITUTE VARCHAR(255));