ALTER TABLE WSL_GENINFO ADD (
    SPECIALITYREFERRALRESPONSEID   VARCHAR2(255) DEFAULT NULL,
    SPECIALITYREFERRALOFFLINEID    VARCHAR2(255) DEFAULT NULL,
    SPECIALITYREFERRALOFFLINEDATE  TIMESTAMP DEFAULT NULL
);
