ALTER TABLE NPHIES_BENEFICIARY ADD (
OCCUPATION varchar(20) NULL,
RELIGION varchar(5)
);

ALTER TABLE NPHIES_CLAIMDIAGNOSIS ADD (
CONDITIONONSET varchar(10));

ALTER TABLE NPHIES_CLAIMITEM ADD (
ISMATERNITY varchar(10) NULL);

Create table NPHIES_COVERAGE_CLASS (
	COVERAGECLASSID varchar(20) NOT NULL,
	TYPE varchar(50) NOT NULL,
	VALUE varchar(250) NOT NULL,
	NAME varchar(250),
	COVERAGEID varchar(20) NOT NULL,
 Constraint PK_COVERAGE_CLASS primary key (COVERAGECLASSID)
);

Alter table NPHIES_COVERAGE_CLASS add Constraint FK_NPHIES_COVERAGE_CLASS foreign key (COVERAGEID) references NPHIES_COVERAGE (COVERAGEID);


Alter table NPHIES_CLAIMENCOUNTERS DROP COLUMN HOSPITALADMISSIONSPECIALITY;
Alter table NPHIES_CLAIMENCOUNTERS DROP COLUMN HOSPITALDISCHARGESPECIALITY;
Alter table NPHIES_CLAIMENCOUNTERS DROP COLUMN HOSPITALINTENDEDLENGTHOFSTAY;
Alter table NPHIES_CLAIMENCOUNTERS DROP COLUMN HOSPITALIZATIONORIGIN;
Alter table NPHIES_CLAIMENCOUNTERS DROP COLUMN HOSPITALADMISSIONSOURCE;
Alter table NPHIES_CLAIMENCOUNTERS DROP COLUMN HOSPITALREADMISSION;
Alter table NPHIES_CLAIMENCOUNTERS DROP COLUMN HOSPITALDISCHARGEDISPOSITION;

ALTER TABLE NPHIES_CLAIMENCOUNTERS ADD (
CAUSEOFDEATH varchar(10) NULL,
SERVICEEVENTTYPE varchar(10) NULL
);
CREATE INDEX IDX_ENCOUNTERS_ENCOUNTERID ON NPHIES_CLAIMENCOUNTERS(ENCOUNTERID);
Alter table NPHIES_CLAIMENCOUNTERS add Constraint UNIQUE_ENCOUNTERS_ENCOUNTERID UNIQUE (ENCOUNTERID);


Create table NPHIES_ENCOUNTERHOSPITALIZATION (
	ENCOUNTERHOSPITALIZATIONID varchar(20) NOT NULL,
	HOSPITALADMISSIONSPECIALITY varchar(20) NOT NULL,
    HOSPITALDISCHARGESPECIALITY varchar(20) NULL,
    HOSPITALINTENDEDLENGTHOFSTAY varchar(20) NOT NULL,
    HOSPITALIZATIONORIGIN varchar(20) NULL,
    HOSPITALADMISSIONSOURCE varchar(20) NOT  NULL,
    HOSPITALREADMISSION varchar(20) NULL,
    HOSPITALDISCHARGEDISPOSITION varchar(20) NULL,
	ENCOUNTERID varchar(20) NOT NULL,
Constraint PK_ENCOUNTERHOSPITALIZATION primary key (ENCOUNTERHOSPITALIZATIONID)
);

Alter table NPHIES_ENCOUNTERHOSPITALIZATION add Constraint FK_ENCOUNTERHOSPITALIZATION foreign key (ENCOUNTERID) references NPHIES_CLAIMENCOUNTERS (ENCOUNTERID);

Create table NPHIES_ENCOUNTEREMERGENCY (
	ENCOUNTEREMERGENCYID varchar(20) NOT NULL,
	EMERGENCYARRIVALCODE varchar(20) NOT NULL,
	EMERGENCYSERVICESTART Datetime NOT NULL,
	EMERGENCYDEPARTMENTDISPOSITION varchar(20) NULL,
	TRIAGECATEGORY varchar(20) NOT NULL,
	TRIAGEDATE Datetime NOT NULL,
	ENCOUNTERID varchar(20) NOT NULL,
 Constraint PK_ENCOUNTEREMERGENCY primary key (ENCOUNTEREMERGENCYID)
);

Alter table NPHIES_ENCOUNTEREMERGENCY add Constraint FK_ENCOUNTERMERGENCY foreign key (ENCOUNTERID) references NPHIES_CLAIMENCOUNTERS (ENCOUNTERID);
