
-- MARITAL STATUS Mandatory
-- OCCUPATION - 'unknown'
-- RELIGION - '98' ('NOT AVAILABLE')
CREATE OR REPLACE VIEW NPHIES_BENEFICIARY (BENEFICIARYID, PATIENTFILENO, FIRSTNAME, MIDDLENAME, LASTNAME,
		FULLNAME, DOB, GENDER, NATIONALITY, DOCUMENTID, DOCUMENTTYPE, CONTACTNUMBER, EHEALTHID,
		RESIDENCYTYPE, MARITALSTATUS, BLOODGROUP, PREFERREDLANGUAGE, EMAIL, ADDRESSLINE,
		ADDRESSSTREETNAME, ADDRESSCITY, ADDRESSDISTRICT, ADDRESSSTATE, ADDRESSPOSTALCODE, ADDRESSCOUNTRY, PROVCLAIMNO, OCCUPATION, RELIGION) AS
	SELECT ROW_NUMBER() OVER (ORDER BY PROVCLAIMNO) AS BENEFICIARYID, PATFILENO AS PATIENTFILENO, FIRSTNAME, MIDDLENAME, LASTNAME, FULLNAME,
		MEMBERDOB AS DOB, GENDER, NATIONALITY AS NATIONALITY, NATIONALID AS DOCUMENTID, NULL, NULL, NULL, NULL, NULL,
		NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, PROVCLAIMNO, 'unknown' AS OCCUPATION, '98' AS RELIGION
	FROM WSL_GENINFO;

-- POLICY HOLDER - ACCCODE (MANDATORY)
CREATE OR REPLACE VIEW NPHIES_COVERAGE (COVERAGEID, MEMBERID, EXPIRYDATE, PAYERNPHIESID,
		TPANPHIESID, RELATIONWITHSUBSCRIBER, POLICYNUMBER, POLICYHOLDER, COVERAGETYPE, BENEFICIARYID, PROVCLAIMNO) AS
	SELECT NPHIES_BENEFICIARY.BENEFICIARYID AS COVERAGEID, MEMBERID AS MEMBERID, NULL, PAYERID AS PAYERNPHIESID, TPAID AS TPANPHIESID, NULL, POLICYNO AS POLICYNUMBER,
		ACCCODE AS POLICYHOLDER, 'EHCPOL' AS COVERAGETYPE, NPHIES_BENEFICIARY.BENEFICIARYID AS BENEFICIARYID, WSL_GENINFO.PROVCLAIMNO
	FROM WSL_GENINFO LEFT JOIN NPHIES_BENEFICIARY ON WSL_GENINFO.PROVCLAIMNO=NPHIES_BENEFICIARY.PROVCLAIMNO;


-- TYPE - CHI Inquiry 'class'
-- VALUE - from CHI Inquiry 'ClassName'
CREATE OR REPLACE VIEW NPHIES_COVERAGE_CLASS (COVERAGEID, TYPE, VALUE, NAME) AS
	SELECT NULL AS TYPE, NULL AS VALUE ,NULL AS NAME, NULL AS COVERAGEID
	FROM WSL_GENINFO WHERE PROVCLAIMNO = '-9999999999999';


CREATE OR REPLACE VIEW NPHIES_PROVCLAIMNO_SERVICEDATE(PROVCLAIMNO,SERVICEDATE) AS
    SELECT WG.PROVCLAIMNO, MIN(WSD.SERVICEDATE) FROM WSL_GENINFO WG
    JOIN WSL_INVOICES WI ON WI.PROVCLAIMNO = WG.PROVCLAIMNO
    JOIN WSL_SERVICE_DETAILS WSD ON WI.INVOICENO = WSD.INVOICENO GROUP BY WG.PROVCLAIMNO;


CREATE OR REPLACE VIEW NPHIES_CLAIMINFO (PROVCLAIMNO, EPISODEID, ISNEWBORN, CLAIMTYPE,
		CLAIMSUBTYPE, PROVIDERNPHIESID, CLAIMCREATEDDATE, ACCOUNTINGPERIOD, BILLABLEPERIODSTART, BILLABLEPERIODEND,
		ELIGIBILITYRESPONSEID, ELIGIBILITYIDENTIFIERURL, ELIGIBILITYOFFLINEID, ELIGIBILITYOFFLINEDATE,
		PREAUTHOFFLINEDATE, PREAUTHRESPONSEID, PREAUTHIDENTIFIERURL, PAYEETYPE, PAYEEID, COVERAGEID, BENEFICIARYID, SUBSCRIBERID, TOTAL,ISREFERRAL,REFERRINGPROVIDERNAME ,PRESCRIPTION) AS
	SELECT WSL_GENINFO.PROVCLAIMNO, WSL_GENINFO.PROVCLAIMNO AS EPISODEID, NULL, DEPTCODE AS CLAIMTYPE,
		CLAIMTYPE AS CLAIMSUBTYPE, PROVIDERID AS PROVIDERNPHIESID, CLAIMDATE AS CLAIMCREATEDDATE, CLAIMDATE AS ACCOUNTINGPERIOD, NULL,
		NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'provider' AS PAYEETYPE, PROVIDERID AS PAYEEID , NPHIES_COVERAGE.COVERAGEID AS COVERAGEID, 
		NPHIES_BENEFICIARY.BENEFICIARYID AS BENEFICIARYID,NULL, TOTCLAIMNETAMT AS TOTAL ,NULL AS ISREFERRAL,NULL AS REFERRINGPROVIDERNAME,NULL AS PRESCRIPTION
	FROM WSL_GENINFO LEFT JOIN NPHIES_BENEFICIARY ON WSL_GENINFO.PROVCLAIMNO=NPHIES_BENEFICIARY.PROVCLAIMNO 
	LEFT JOIN NPHIES_COVERAGE ON NPHIES_BENEFICIARY.BENEFICIARYID=NPHIES_COVERAGE.BENEFICIARYID;

-- CONDITIONONSET - NULL
CREATE OR REPLACE VIEW NPHIES_CLAIMDIAGNOSIS (PROVCLAIMNO, SEQUENCENO, DIAGNOSISCODE, DIAGNOSISDESC, 
		DIAGNOSISTYPE, ONADMISSION, CONDITIONONSET) AS
	SELECT PROVCLAIMNO, ROW_NUMBER() OVER (ORDER BY PROVCLAIMNO), DIAGNOSISCODE, DIAGNOSISDESC, NULL, NULL, NULL AS CONDITIONONSET
	FROM WSL_CLAIM_DIAGNOSIS;

CREATE OR REPLACE VIEW NPHIES_CLAIMPREAUTHDETAILS (PROVCLAIMNO, PREAUTHREFNO) AS
	SELECT PROVCLAIMNO, APPREFNO AS PREAUTHREFNO
	FROM WSL_GENINFO WHERE APPREFNO IS NOT NULL AND APPREFNO != '';

CREATE OR REPLACE VIEW NPHIES_CLAIMCARETEAM(PROVCLAIMNO, SEQUENCENO, PHYSICIANID, PHYSICIANNAME, 
		PRACTITIONERROLE, CARETEAMROLE, CARETEAMQUALIFICATION) AS
	SELECT PROVCLAIMNO, ROW_NUMBER() OVER (ORDER BY PROVCLAIMNO), PHYID AS PHYSICIANID, PHYNAME AS PHYSICIANNAME, 
		'doctor', 'primary', DEPTCODE AS CARETEAMQUALIFICATION
	FROM WSL_GENINFO;

-- ISMATERNITY  - SPECIFIC DIAGNOSIS CODE AND DEPARTMENT IS OBGYN
CREATE OR REPLACE VIEW NPHIES_CLAIMITEM(PROVCLAIMNO, INVOICENO, SEQUENCENO, SERVICETYPE, SERVICECODE, SERVICEDESC,
		NONSTANDARDCODE, NONSTANDARDDESC, UDI, ISPACKAGE, QUANTITY, QUANTITYCODE, UNITPRICE, 
		DISCOUNT, FACTOR, PATIENTSHARE, PAYERSHARE, TAX, NET, STARTDATE, ENDDATE,
		BODYSITECODE, SUBSITECODE, DRUGSELECTIONREASON, PRESCRIBEDDRUGCODE , PHARMACISTSELECTIONREASON, PHARMACISTSUBSTITUTE, REASONPHARMACISTSUBSTITUTE, ISMATERNITY) AS
	SELECT WI.PROVCLAIMNO, WI.INVOICENO, ROW_NUMBER() OVER (ORDER BY PROVCLAIMNO), NULL AS SERVICETYPE, NULL AS SERVICECODE, NULL AS SERVICEDESC,
		WSD.SERVICECODE AS NONSTANDARDCODE, WSD.SERVICEDESC AS NONSTANDARDDESC, NULL AS UDI, 'false' AS ISPACKAGE,
		WSD.QTY AS QUANTITY, 'package' AS QUANTITYCODE, WSD.UNITSERVICEPRICE AS UNITPRICE, WSD.TOTSERVICEDISC AS DISCOUNT, NULL AS FACTOR, 
		WSD.TOTSERVICEPATSHARE AS PATIENTSHARE, (IFNULL(WSD.TOTSERVICEGRSAMT,0)-IFNULL(WSD.TOTSERVICEDISC,0)-IFNULL(WSD.TOTSERVICEPATSHARE,0)+IFNULL(WSD.TOTSERVICENETVATAMOUNT,0)) AS PAYERSHARE, 
		WSD.TOTSERVICENETVATAMOUNT AS TAX, NULL AS NET, WSD.SERVICEDATE AS STARTDATE,
		WSD.SERVICEDATE AS ENDDATE, WSD.TOOTHNO AS BODYSITECODE, NULL, NULL, NULL,
		NULL, 
        NULL, 
        NULL,
        NULL AS ISMATERNITY
	FROM WSL_INVOICES WI 
    LEFT JOIN WSL_SERVICE_DETAILS WSD ON WI.INVOICENO = WSD.INVOICENO
    LEFT JOIN NPHIES_CLAIMPREAUTHDETAILS ON NPHIES_CLAIMPREAUTHDETAILS.PROVCLAIMNO = WI.PROVCLAIMNO;


-- Supporting info 
DELIMITER $$

DROP PROCEDURE IF EXISTS `generate_supporting_info` $$
CREATE PROCEDURE `generate_supporting_info` ()
DETERMINISTIC
BEGIN

DECLARE var_table_count INT;
SELECT COUNT(*) INTO @var_table_count FROM information_schema.tables WHERE table_schema = 'wslmidtables' and TABLE_NAME = 'wsl_claim_attachment';
IF (@var_table_count > 0) THEN
SET @supporting_query = 'CREATE OR REPLACE VIEW NPHIES_CLAIMSUPPORTINGINFO (PROVCLAIMNO, SEQUENCENO, CATEGORY, REASON,
			SUPPORTINGVALUE, SUPPORTINGATTACHMENT, ATTACHMENTFILENAME, ATTACHMENTTYPE, CODE,
			TIMINGPERIODFROM, TIMINGPERIODTO) AS 
		SELECT PROVCLAIMNO AS PROVCLAIMNO , ROW_NUMBER() OVER(ORDER BY (SELECT 1)) AS SEQUENCENO, SUPPORTTYPE, REASON, SUPPORTINGVALUE, FILECONTENT, FILENAME,
		NULL AS ATTACHMENTTYPE,CODE,TIMINGPERIODFROM, TIMINGPERIODTO 
		FROM (
			SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "temperature" AS SUPPORTTYPE, NULL AS REASON,
			CONVERT(TEMPERATURE, CHAR) AS SUPPORTINGVALUE, NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, "Cel" AS CODE, 
			 NPS.SERVICEDATE AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO
			FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO WHERE WG.TEMPERATURE IS NOT NULL
		UNION ALL 
			SELECT PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "chief-complaint" AS SUPPORTTYPE, NULL AS REASON, MAINSYMPTOM AS SUPPORTINGVALUE,
			NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, NULL AS CODE, NULL AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO
			FROM WSL_GENINFO WHERE MAINSYMPTOM IS NOT NULL AND MAINSYMPTOM != ''''
		UNION ALL
            SELECT PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "patient-history", NULL AS REASON, MAINSYMPTOM AS SUPPORTINGVALUE, NULL, NULL, NULL, NULL, NULL, NULL
            FROM WSL_GENINFO WHERE MAINSYMPTOM IS NOT NULL AND MAINSYMPTOM != ''''
        UNION ALL
            SELECT PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "history-of-present-illness", NULL AS REASON, MAINSYMPTOM AS SUPPORTINGVALUE, NULL, NULL, NULL, NULL, NULL, NULL
            FROM WSL_GENINFO WHERE MAINSYMPTOM IS NOT NULL AND MAINSYMPTOM != ''''
        UNION ALL
            SELECT WSG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "treatment-plan", NULL AS REASON,
           (SELECT GROUP_CONCAT(concat_ws(" - ", WSD.SERVICECODE, WSD.SERVICEDESC) ORDER BY WSD.SERVICECODE ASC SEPARATOR ", ")
            FROM WSL_SERVICE_DETAILS WSD JOIN WSL_INVOICES WI ON WSD.INVOICENO = WI.INVOICENO
            JOIN WSL_GENINFO WG ON WI.PROVCLAIMNO = WG.PROVCLAIMNO where WSD.SERVICECODE IS NOT NULL AND WSD.SERVICEDESC IS NOT NULL AND WG.PROVCLAIMNO = WSG.PROVCLAIMNO)
            AS SUPPORTINGVALUE, NULL, NULL, NULL, NULL, NULL, NULL FROM WSL_GENINFO WSG
		UNION ALL
			SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "vital-sign-weight" AS SUPPORTTYPE, NULL AS REASON,
			CONVERT(WEIGH, CHAR) AS SUPPORTINGVALUE, NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, "kg" AS CODE, NPS.SERVICEDATE AS TIMINGPERIODFROM,
			NULL AS TIMINGPERIODTO
			FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO WHERE WG.WEIGH IS NOT NULL AND WEIGH != 0
		UNION ALL
        	-- TIMINGPERIODFROM - min (serviceDate from service_details)
            SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "vital-sign-height", ''999.9'' AS REASON, NULL, NULL, NULL, NULL, NULL,
            NPS.SERVICEDATE AS TIMINGPERIODFROM, NULL
            FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO
        UNION ALL
            -- TIMINGPERIODFROM - min (serviceDate from service_details)
            SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "oxygen-saturation", ''999'' AS REASON, NULL, NULL, NULL, NULL, NULL,
            NPS.SERVICEDATE AS TIMINGPERIODFROM, NULL
            FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO
		UNION ALL
		    -- should be removed after deployment of MDS changes
			SELECT PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "hospitalized" AS SUPPORTTYPE, NULL AS REASON, NULL AS SUPPORTINGVALUE, NULL AS FILECONTENT,
			NULL AS FILENAME, NULL AS ATTACHMENTTYPE, NULL AS CODE, 
			ADMISSIONDATE AS TIMINGPERIODFROM, DISCHARGEDATE AS TIMINGPERIODTO
			FROM WSL_GENINFO WHERE ADMISSIONDATE IS NOT NULL AND DISCHARGEDATE IS NOT NULL
		UNION ALL
		    -- significantsign - physical examnation
            SELECT PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "physical-examination" AS SUPPORTTYPE, NULL AS REASON, CONVERT(SIGNIFICANTSIGN, CHAR), NULL AS FILECONTENT,
             NULL, NULL, NULL, NULL, NULL FROM WSL_GENINFO WHERE SIGNIFICANTSIGN IS NOT NULL AND SIGNIFICANTSIGN != ''''
        UNION ALL
			SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "pulse" AS SUPPORTTYPE, NULL AS REASON, CONVERT(PULSE, CHAR) AS SUPPORTINGVALUE, NULL AS FILECONTENT,
            NULL AS FILENAME, NULL AS ATTACHMENTTYPE, "/min" AS CODE,  NPS.SERVICEDATE AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO
            FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO WHERE PULSE IS NOT NULL AND PULSE != 0
		UNION ALL
			SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "respiratory-rate" AS SUPPORTTYPE, NULL AS REASON, CONVERT(RESPIRATORYRATE, CHAR) AS SUPPORTINGVALUE,
			NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, "/min" AS CODE,
			NPS.SERVICEDATE AS TIMINGPERIODFROM, NULL
                FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO WHERE WG.RESPIRATORYRATE IS NOT NULL AND RESPIRATORYRATE != 0
        UNION ALL
			SELECT PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "info" AS SUPPORTTYPE, NULL AS REASON, CONVERT(RADIOREPORT, CHAR) AS SUPPORTINGVALUE, NULL AS FILECONTENT,
			NULL AS FILENAME, NULL AS ATTACHMENTTYPE, NULL AS CODE, NULL AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO
			FROM WSL_GENINFO WHERE RADIOREPORT IS NOT NULL AND LENGTH(TRIM(RADIOREPORT)) > 0
		UNION ALL
			SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "vital-sign-systolic" AS SUPPORTTYPE, NULL AS REASON, CONVERT(BLOODPRESSURE, CHAR) AS SUPPORTINGVALUE,
			NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, "mm[Hg]" AS CODE,
			NPS.SERVICEDATE AS TIMINGPERIODFROM, NULL
                	FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO WHERE
                	 WG.BLOODPRESSURE IS NOT NULL AND BLOODPRESSURE != ''''
		UNION ALL
			SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "vital-sign-diastolic" AS SUPPORTTYPE, NULL AS REASON, CONVERT(BLOODPRESSURE, CHAR) AS SUPPORTINGVALUE,
			NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, "mm[Hg]" AS CODE, NPS.SERVICEDATE AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO
			FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO WHERE
			    BLOODPRESSURE IS NOT NULL AND BLOODPRESSURE != ''''
		UNION ALL
			select PROVCLAIMNO_temp AS PROVCLAIMNO, NULL AS SEQUENCENO, "lab-test" AS SUPPORTTYPE, NULL AS REASON,
			case
			when LABCOMPCODE_temp is not null THEN (CONCAT(''LABCODE: '', LABCOMPCODE_temp, '' ,LABDESC: '',  LABCOMPDESC_temp , '' ,LABRESULT: '', LABRESULT_temp, '' ,LABRESULTUNIT: '', LABRESULTUNIT_temp, '' ,LABRESULTCOMMENT: '', LABRESULTCOMMENT_temp, '' ,LABRESULTCDESC: '', LABRESULTDESC_temp))
			when LABCOMPDESC_temp is not null THEN (CONCAT(''LABCODE: '', LABCOMPCODE_temp, '' ,LABDESC: '',  LABCOMPDESC_temp , '' ,LABRESULT: '', LABRESULT_temp, '' ,LABRESULTUNIT: '', LABRESULTUNIT_temp, '' ,LABRESULTCOMMENT: '', LABRESULTCOMMENT_temp, '' ,LABRESULTCDESC: '', LABRESULTDESC_temp))
			when LABRESULT_temp is not null THEN (CONCAT(''LABCODE: '', LABCOMPCODE_temp, '' ,LABDESC: '',  LABCOMPDESC_temp , '' ,LABRESULT: '', LABRESULT_temp, '' ,LABRESULTUNIT: '', LABRESULTUNIT_temp, '' ,LABRESULTCOMMENT: '', LABRESULTCOMMENT_temp, '' ,LABRESULTCDESC: '', LABRESULTDESC_temp))
			when LABRESULTUNIT_temp is not null THEN (CONCAT(''LABCODE: '', LABCOMPCODE_temp, '' ,LABDESC: '',  LABCOMPDESC_temp , '' ,LABRESULT: '', LABRESULT_temp, '' ,LABRESULTUNIT: '', LABRESULTUNIT_temp, '' ,LABRESULTCOMMENT: '', LABRESULTCOMMENT_temp, '' ,LABRESULTCDESC: '', LABRESULTDESC_temp))
			when LABRESULTCOMMENT_temp is not null THEN (CONCAT(''LABCODE: '', LABCOMPCODE_temp, '' ,LABDESC: '',  LABCOMPDESC_temp , '' ,LABRESULT: '', LABRESULT_temp, '' ,LABRESULTUNIT: '', LABRESULTUNIT_temp, '' ,LABRESULTCOMMENT: '', LABRESULTCOMMENT_temp, '' ,LABRESULTCDESC: '', LABRESULTDESC_temp))
			when LABRESULTDESC_temp is not null THEN (CONCAT(''LABCODE: '', LABCOMPCODE_temp, '' ,LABDESC: '',  LABCOMPDESC_temp , '' ,LABRESULT: '', LABRESULT_temp, '' ,LABRESULTUNIT: '', LABRESULTUNIT_temp, '' ,LABRESULTCOMMENT: '', LABRESULTCOMMENT_temp, '' ,LABRESULTCDESC: '', LABRESULTDESC_temp))
			END AS SUPPORTINGVALUE, NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, CODE_temp AS CODE, TimePeriodFromDate AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO
			from (
				SELECT labResult.PROVCLAIMNO AS PROVCLAIMNO_temp,labComponent.LABCOMPCODE AS LABCOMPCODE_temp, labComponent.LABCOMPDESC AS LABCOMPDESC_temp, 
				labComponent.LABRESULT AS LABRESULT_temp, labComponent.LABRESULTUNIT AS LABRESULTUNIT_temp, labComponent.LABRESULTCOMMENT AS LABRESULTCOMMENT_temp, labResult.LABDESC AS LABRESULTDESC_temp,
				labResult.LABTESTCODE AS CODE_temp, NPS.SERVICEDATE AS TimePeriodFromDate
				FROM WSL_LAB_RESULT labResult LEFT JOIN WSL_LAB_COMPONENT labComponent ON labResult.LABTESTCODE=labComponent.LABTESTCODE and labResult.SERIAL=labComponent.SERIAL and labResult.PROVCLAIMNO=labComponent.PROVCLAIMNO
				JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = labResult.PROVCLAIMNO) as s1
		UNION ALL
			SELECT PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "last-menstrual-period" AS SUPPORTTYPE, NULL AS REASON, NULL AS SUPPORTINGVALUE,
			NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, NULL AS CODE, LASTMENSTRUATIONPERIOD AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO
			FROM WSL_GENINFO WHERE LASTMENSTRUATIONPERIOD IS NOT NULL AND LASTMENSTRUATIONPERIOD != 0
		UNION ALL
		SELECT PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "attachment" AS SUPPORTTYPE, NULL AS REASON, NULL AS SUPPORTINGVALUE, FILECONTENT AS FILECONTENT,
		FILENAME AS FILENAME, NULL AS ATTACHMENTTYPE, NULL AS CODE, NULL AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO
		FROM WSL_CLAIM_ATTACHMENT WHERE FILENAME IS NOT NULL ) as supportingValue';

PREPARE my_query FROM @supporting_query;
EXECUTE my_query;

ELSE
SET @supporting_query = 'CREATE OR REPLACE VIEW NPHIES_CLAIMSUPPORTINGINFO (PROVCLAIMNO, SEQUENCENO, CATEGORY, REASON,
			SUPPORTINGVALUE, SUPPORTINGATTACHMENT, ATTACHMENTFILENAME, ATTACHMENTTYPE, CODE,
			TIMINGPERIODFROM, TIMINGPERIODTO,UNIT) AS
		SELECT PROVCLAIMNO AS PROVCLAIMNO , ROW_NUMBER() OVER(ORDER BY (SELECT 1)) AS SEQUENCENO, SUPPORTTYPE, REASON, SUPPORTINGVALUE, FILECONTENT, FILENAME,
		NULL AS ATTACHMENTTYPE, CODE, TIMINGPERIODFROM, TIMINGPERIODTO ,UNIT
		FROM (
			SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "temperature" AS SUPPORTTYPE, NULL AS REASON,
			CONVERT(TEMPERATURE, CHAR) AS SUPPORTINGVALUE, NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, "Cel" AS CODE, 
			NPS.SERVICEDATE AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO , NULL AS UNIT
			FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO WHERE TEMPERATURE IS NOT NULL
		UNION ALL 
			SELECT PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "chief-complaint" AS SUPPORTTYPE, NULL AS REASON, MAINSYMPTOM AS SUPPORTINGVALUE,
			NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, NULL AS CODE, NULL AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO, NULL AS UNIT
			FROM WSL_GENINFO WHERE MAINSYMPTOM IS NOT NULL AND MAINSYMPTOM != ''''
        UNION ALL
            SELECT PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "patient-history", NULL AS REASON, MAINSYMPTOM AS SUPPORTINGVALUE, NULL, NULL, NULL, NULL, NULL, NULL,NULL
            FROM WSL_GENINFO WHERE MAINSYMPTOM IS NOT NULL AND MAINSYMPTOM != ''''
        UNION ALL
            SELECT PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "history-of-present-illness", NULL AS REASON, MAINSYMPTOM AS SUPPORTINGVALUE, NULL, NULL, NULL, NULL, NULL, NULL,NULL
            FROM WSL_GENINFO WHERE MAINSYMPTOM IS NOT NULL AND MAINSYMPTOM != ''''
        UNION ALL
            SELECT WSG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "treatment-plan", NULL AS REASON,
            (SELECT GROUP_CONCAT(concat_ws(" - ", WSD.SERVICECODE, WSD.SERVICEDESC) ORDER BY WSD.SERVICECODE ASC SEPARATOR ", ")
            FROM WSL_SERVICE_DETAILS WSD JOIN WSL_INVOICES WI ON WSD.INVOICENO = WI.INVOICENO
            JOIN WSL_GENINFO WG ON WI.PROVCLAIMNO = WG.PROVCLAIMNO where WSD.SERVICECODE IS NOT NULL AND WSD.SERVICEDESC IS NOT NULL AND WG.PROVCLAIMNO = WSG.PROVCLAIMNO)
            AS SUPPORTINGVALUE, NULL, NULL, NULL, NULL, NULL, NULL,NULL FROM WSL_GENINFO WSG
		UNION ALL
			SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "vital-sign-weight" AS SUPPORTTYPE, NULL AS REASON,
			CONVERT(WEIGH, CHAR) AS SUPPORTINGVALUE, NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, "kg" AS CODE, NPS.SERVICEDATE AS TIMINGPERIODFROM,
			NULL AS TIMINGPERIODTO, NULL AS UNIT FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO
			WHERE WEIGH IS NOT NULL AND WEIGH != 0
		UNION ALL
        	-- TIMINGPERIODFROM - min (serviceDate from service_details)
            SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "vital-sign-height", ''999.9'' AS REASON, NULL, NULL, NULL, NULL, NULL,
            NPS.SERVICEDATE AS TIMINGPERIODFROM, NULL,NULL
            FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO
        UNION ALL
            -- TIMINGPERIODFROM - min (serviceDate from service_details)
            SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "oxygen-saturation", ''999'' AS REASON, NULL, NULL, NULL, NULL, NULL,
            NPS.SERVICEDATE AS TIMINGPERIODFROM, NULL,NULL
            FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO
		UNION ALL
            -- significantsign - physical examnation
            SELECT PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "physical-examination", NULL AS REASON, CONVERT(SIGNIFICANTSIGN, CHAR), NULL, NULL, NULL, NULL, NULL, NULL, NULL
            FROM WSL_GENINFO WHERE SIGNIFICANTSIGN IS NOT NULL AND SIGNIFICANTSIGN != ''''
		UNION ALL
			SELECT PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "hospitalized" AS SUPPORTTYPE, NULL AS REASON, NULL AS SUPPORTINGVALUE, NULL AS FILECONTENT,
			NULL AS FILENAME, NULL AS ATTACHMENTTYPE, NULL AS CODE, 
			ADMISSIONDATE AS TIMINGPERIODFROM, DISCHARGEDATE AS TIMINGPERIODTO,  NULL AS UNIT
			FROM WSL_GENINFO WHERE ADMISSIONDATE IS NOT NULL AND DISCHARGEDATE IS NOT NULL
		UNION ALL
			SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "pulse" AS SUPPORTTYPE, NULL AS REASON, CONVERT(PULSE, CHAR) AS SUPPORTINGVALUE, NULL AS FILECONTENT,
			NULL AS FILENAME, NULL AS ATTACHMENTTYPE, "/min" AS CODE,  NPS.SERVICEDATE AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO,  NULL AS UNIT
			FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO WHERE PULSE IS NOT NULL AND PULSE != 0
		UNION ALL
			SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "respiratory-rate" AS SUPPORTTYPE, NULL AS REASON, CONVERT(RESPIRATORYRATE, CHAR) AS SUPPORTINGVALUE,
			NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, "/min" AS CODE, NPS.SERVICEDATE AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO,  NULL AS UNIT
			FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO WHERE WG.RESPIRATORYRATE IS NOT NULL AND WG.RESPIRATORYRATE != 0
		UNION ALL
			SELECT PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "info" AS SUPPORTTYPE, NULL AS REASON, CONVERT(RADIOREPORT, CHAR) AS SUPPORTINGVALUE, NULL AS FILECONTENT,
			NULL AS FILENAME, NULL AS ATTACHMENTTYPE, NULL AS CODE, NULL AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO,  NULL AS UNIT
			FROM WSL_GENINFO WHERE RADIOREPORT IS NOT NULL AND LENGTH(TRIM(RADIOREPORT)) > 0
		UNION ALL
			SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "vital-sign-systolic" AS SUPPORTTYPE, NULL AS REASON, CONVERT(BLOODPRESSURE, CHAR) AS SUPPORTINGVALUE,
			NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, "mm[Hg]" AS CODE, NPS.SERVICEDATE AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO,  NULL AS UNIT
			FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO WHERE BLOODPRESSURE IS NOT NULL AND BLOODPRESSURE != ''''
		UNION ALL
			SELECT WG.PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "vital-sign-diastolic" AS SUPPORTTYPE, NULL AS REASON, CONVERT(BLOODPRESSURE, CHAR) AS SUPPORTINGVALUE,
			NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, "mm[Hg]" AS CODE, NPS.SERVICEDATE AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO,  NULL AS UNIT
			FROM WSL_GENINFO WG JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO WHERE BLOODPRESSURE IS NOT NULL AND BLOODPRESSURE != ''''
		UNION ALL
			select PROVCLAIMNO_temp AS PROVCLAIMNO, NULL AS SEQUENCENO, "lab-test" AS SUPPORTTYPE, NULL AS REASON,
			case
			when LABCOMPCODE_temp is not null THEN (CONCAT(''LABCODE: '', LABCOMPCODE_temp, '' ,LABDESC: '',  LABCOMPDESC_temp , '' ,LABRESULT: '', LABRESULT_temp, '' ,LABRESULTUNIT: '', LABRESULTUNIT_temp, '' ,LABRESULTCOMMENT: '', LABRESULTCOMMENT_temp, '' ,LABRESULTCDESC: '', LABRESULTDESC_temp))
			when LABCOMPDESC_temp is not null THEN (CONCAT(''LABCODE: '', LABCOMPCODE_temp, '' ,LABDESC: '',  LABCOMPDESC_temp , '' ,LABRESULT: '', LABRESULT_temp, '' ,LABRESULTUNIT: '', LABRESULTUNIT_temp, '' ,LABRESULTCOMMENT: '', LABRESULTCOMMENT_temp, '' ,LABRESULTCDESC: '', LABRESULTDESC_temp))
			when LABRESULT_temp is not null THEN (CONCAT(''LABCODE: '', LABCOMPCODE_temp, '' ,LABDESC: '',  LABCOMPDESC_temp , '' ,LABRESULT: '', LABRESULT_temp, '' ,LABRESULTUNIT: '', LABRESULTUNIT_temp, '' ,LABRESULTCOMMENT: '', LABRESULTCOMMENT_temp, '' ,LABRESULTCDESC: '', LABRESULTDESC_temp))
			when LABRESULTUNIT_temp is not null THEN (CONCAT(''LABCODE: '', LABCOMPCODE_temp, '' ,LABDESC: '',  LABCOMPDESC_temp , '' ,LABRESULT: '', LABRESULT_temp, '' ,LABRESULTUNIT: '', LABRESULTUNIT_temp, '' ,LABRESULTCOMMENT: '', LABRESULTCOMMENT_temp, '' ,LABRESULTCDESC: '', LABRESULTDESC_temp))
			when LABRESULTCOMMENT_temp is not null THEN (CONCAT(''LABCODE: '', LABCOMPCODE_temp, '' ,LABDESC: '',  LABCOMPDESC_temp , '' ,LABRESULT: '', LABRESULT_temp, '' ,LABRESULTUNIT: '', LABRESULTUNIT_temp, '' ,LABRESULTCOMMENT: '', LABRESULTCOMMENT_temp, '' ,LABRESULTCDESC: '', LABRESULTDESC_temp))
			when LABRESULTDESC_temp is not null THEN (CONCAT(''LABCODE: '', LABCOMPCODE_temp, '' ,LABDESC: '',  LABCOMPDESC_temp , '' ,LABRESULT: '', LABRESULT_temp, '' ,LABRESULTUNIT: '', LABRESULTUNIT_temp, '' ,LABRESULTCOMMENT: '', LABRESULTCOMMENT_temp, '' ,LABRESULTCDESC: '', LABRESULTDESC_temp))
			END AS SUPPORTINGVALUE, NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, CODE_temp AS CODE, TimePeriodFromDate AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO,  NULL AS UNIT
			from (
				SELECT labResult.PROVCLAIMNO AS PROVCLAIMNO_temp,labComponent.LABCOMPCODE AS LABCOMPCODE_temp, labComponent.LABCOMPDESC AS LABCOMPDESC_temp, 
				labComponent.LABRESULT AS LABRESULT_temp, labComponent.LABRESULTUNIT AS LABRESULTUNIT_temp, labComponent.LABRESULTCOMMENT AS LABRESULTCOMMENT_temp, labResult.LABDESC AS LABRESULTDESC_temp,
				labResult.LABTESTCODE AS CODE_temp, NPS.SERVICEDATE AS TimePeriodFromDate
				FROM WSL_LAB_RESULT labResult LEFT JOIN WSL_LAB_COMPONENT labComponent ON labResult.LABTESTCODE=labComponent.LABTESTCODE and labResult.SERIAL=labComponent.SERIAL and labResult.PROVCLAIMNO=labComponent.PROVCLAIMNO
				JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = labResult.PROVCLAIMNO) as s1
		UNION ALL
			SELECT PROVCLAIMNO AS PROVCLAIMNO, NULL AS SEQUENCENO, "last-menstrual-period" AS SUPPORTTYPE, NULL AS REASON, NULL AS SUPPORTINGVALUE,
			NULL AS FILECONTENT, NULL AS FILENAME, NULL AS ATTACHMENTTYPE, NULL AS CODE, LASTMENSTRUATIONPERIOD AS TIMINGPERIODFROM, NULL AS TIMINGPERIODTO,  NULL AS UNIT
			FROM WSL_GENINFO WHERE LASTMENSTRUATIONPERIOD IS NOT NULL AND LASTMENSTRUATIONPERIOD != 0
	) as supportingValue';
PREPARE my_query FROM @supporting_query;
EXECUTE my_query;
END IF;

END $$
DELIMITER ;

call generate_supporting_info();

-- Accident details
CREATE OR REPLACE VIEW NPHIES_CLAIMACCIDENTDETAIL(PROVCLAIMNO, ACCIDENTTYPE, ACCIDENTDATE,
		ADDRESSSTREETNAME, ADDRESSCITY, ADDRESSSTATE, ADDRESSCOUNTRY) AS
	SELECT NULL AS PROVCLAIMNO, NULL, NULL, NULL, NULL, NULL, NULL
	FROM WSL_GENINFO where PROVCLAIMNO='-9999999999999';

CREATE OR REPLACE VIEW NPHIES_CLAIMVISIONPRESCRIPTION(PROVCLAIMNO, VISIONPRESCRIPTIONID, DATEWRITTEN,
		CARETEAMSEQUENCE, PRODUCT, EYE, SPHERE, CYLINDER, AXIS, PRISMAMOUNT,
		PRISMBASE, MULTIFOCALPOWER, LENSPOWER, LENSBACKCURVE, LENSDIAMETER, LENSDURATION,
		LENSCOLOR, LENSBRAND, LENSNOTE, LENSDURATIONUNIT) AS
	SELECT NULL AS PROVCLAIMNO, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
		NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
	FROM WSL_GENINFO where PROVCLAIMNO='-9999999999999';

CREATE OR REPLACE VIEW NPHIES_ITEMDIAGNOSIS(PROVCLAIMNO, DIAGNOSISSEQUENCENO, ITEMSEQUENCENO) AS
	SELECT NULL AS PROVCLAIMNO , NULL AS DIAGNOSISSEQUENCENO, NULL AS ITEMSEQUENCENO
    FROM WSL_GENINFO where PROVCLAIMNO='-9999999999999';

CREATE OR REPLACE VIEW NPHIES_ITEMCARETEAM(PROVCLAIMNO, CARETEAMSEQUENCENO, ITEMSEQUENCENO) AS
	SELECT NULL AS PROVCLAIMNO , NULL AS CARETEAMSEQUENCENO, NULL AS ITEMSEQUENCENO
    FROM WSL_GENINFO where PROVCLAIMNO='-9999999999999';

CREATE OR REPLACE VIEW NPHIES_ITEMSUPPORTINGINFO(PROVCLAIMNO, SUPPORTINGINFOSEQUENCENO, ITEMSEQUENCENO) AS
	SELECT NULL AS PROVCLAIMNO , NULL AS SUPPORTINGINFOSEQUENCENO, NULL AS ITEMSEQUENCENO
    FROM WSL_GENINFO where PROVCLAIMNO='-9999999999999';

CREATE OR REPLACE VIEW NPHIES_CLAIMITEMDETAILS(ITEMSEQUENCENO, PROVCLAIMNO, SEQUENCENO,
		SERVICETYPE, SERVICECODE, SERVICEDESC, NONSTANDARDCODE, NONSTANDARDDESC, UDI, 
		QUANTITY, QUANTITYCODE, UNITPRICE, TAX, NET , PHARMACISTSELECTIONREASON , PHARMACISTSUBSTITUTE ,REASONPHARMACISTSUBSTITUTE,PRESCRIBEDDRUGCODE) AS
	SELECT NULL, NULL AS PROVCLAIMNO, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
		NULL, NULL, NULL , NULL , NULL, NULL, NULL 
	FROM WSL_GENINFO where PROVCLAIMNO='-9999999999999';

-- ENCOUNTERID - PROVCLAIMNO
-- ENCOUNTERSTARTDATE - MIN(SERVICEDATE)
-- ENCOUNTERSTATUS - 'unknown'
-- ENCOUNTERCLASS - 'AMB'.
-- SERVICEEVENTTYPE - if VISITTYPE = 'new' or 'referral' then 'ICSE' else if VISITTYPE = 'SCSE' else 'ICSE'.
CREATE OR REPLACE VIEW NPHIES_CLAIMENCOUNTERS(PROVCLAIMNO, ENCOUNTERID, ENCOUNTERSTARTDATE,
		ENCOUNTERENDDATE, ENCOUNTERCLASS, ENCOUNTERSERVICETYPE, PRIORITY, SERVICEPROVIDER, ENCOUNTERSTATUS, CAUSEOFDEATH, SERVICEEVENTTYPE) AS
	SELECT WG.PROVCLAIMNO AS PROVCLAIMNO,
	WG.PROVCLAIMNO AS ENCOUNTERID,
    NPS.SERVICEDATE AS ENCOUNTERSTARTDATE,
    NULL AS ENCOUNTERENDDATE,
    NULL AS ENCOUNTERCLASS,
	NULL AS ENCOUNTERSERVICETYPE,
	NULL AS PRIORITY,
	NULL AS SERVICEPROVIDER,
	'unknown' as ENCOUNTERSTATUS,
	NULL AS CAUSEOFDEATH,
	CASE
        WHEN (LOWER(WG.VISITTYPE) = 'new') OR (LOWER(WG.VISITTYPE) = 'referral') THEN 'ICSE'
        WHEN (LOWER(WG.VISITTYPE) = 'follow-up') OR (LOWER(WG.VISITTYPE) = 'followup') THEN 'SCSE'
            ELSE 'ICSE'
    END AS SERVICEEVENTTYPE
	FROM WSL_GENINFO WG
	JOIN NPHIES_PROVCLAIMNO_SERVICEDATE NPS ON NPS.PROVCLAIMNO = WG.PROVCLAIMNO;


CREATE OR REPLACE VIEW NPHIESENCOUNTERHOSPITALIZATION (PROVCLAIMNO, ENCOUNTERHOSPITALIZATIONID, HOSPITALADMISSIONSPECIALITY,
     HOSPITALDISCHARGESPECIALITY, HOSPITALINTENDEDLENGTHOFSTAY, HOSPITALIZATIONORIGIN, HOSPITALADMISSIONSOURCE,
     HOSPITALREADMISSION, HOSPITALDISCHARGEDISPOSITION) AS
    SELECT NULL AS PROVCLAIMNO,
    NULL AS ENCOUNTERHOSPITALIZATIONID,
    NULL AS HOSPITALADMISSIONSPECIALITY,
    NULL AS HOSPITALDISCHARGESPECIALITY,
    NULL AS HOSPITALINTENDEDLENGTHOFSTAY,
    NULL AS HOSPITALIZATIONORIGIN,
    NULL AS HOSPITALADMISSIONSOURCE,
    NULL AS HOSPITALREADMISSION,
    NULL AS HOSPITALDISCHARGEDISPOSITION
	FROM WSL_GENINFO
    WHERE PROVCLAIMNO = '-9999999999999';



CREATE OR REPLACE VIEW NPHIES_ENCOUNTEREMERGENCY ( PROVCLAIMNO, ENCOUNTEREMERGENCYID, EMERGENCYARRIVALCODE, EMERGENCYSERVICESTART,
    EMERGENCYDEPARTMENTDISPOSITION, TRIAGECATEGORY, TRIAGEDATE) AS
    SELECT NULL AS PROVCLAIMNO,
    NULL AS ENCOUNTEREMERGENCYID,
    NULL AS EMERGENCYARRIVALCODE,
    NULL AS EMERGENCYSERVICESTART,
    NULL AS EMERGENCYDEPARTMENTDISPOSITION,
    NULL AS TRIAGECATEGORY,
    NULL AS TRIAGEDATE
    FROM WSL_GENINFO WHERE PROVCLAIMNO = '-9999999999999';

	
